# Generated by Django 3.2 on 2021-04-28 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210428_1104'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipie_model',
            name='yt_link',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='YT link'),
        ),
    ]
